#!/usr/bin/env node
// Builds js/icons.js: an inline SVG sprite holding only the icons the app uses.
//
// The icons are Phosphor (MIT, https://phosphoricons.com). Shipping a sprite of
// ~60 symbols instead of the full icon fonts keeps the page small, avoids a
// flash of missing icons while a font loads, and works offline and from file://.
//
// Usage:
//   node tools/build-icons.mjs              # fetch Phosphor 2.1.2 from jsDelivr
//   node tools/build-icons.mjs <dir>        # read <dir>/{regular,fill}/selection.json
//
// To add an icon, add its Phosphor name to ICONS below (append "-fill" for the
// filled weight), run this script, and reference it as <use href="#i-NAME">.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ICONS = [
  // regular weight
  'video-camera', 'monitor', 'monitor-play', 'microphone', 'microphone-slash',
  'microphone-stage', 'camera', 'camera-rotate', 'camera-slash', 'download-simple',
  'share-network', 'trash', 'pencil-simple', 'image', 'x', 'gear', 'sliders',
  'question', 'keyboard', 'film-strip', 'waveform', 'scroll', 'text-aa',
  'picture-in-picture', 'arrow-counter-clockwise', 'hard-drives', 'info', 'warning',
  'check-circle', 'warning-circle', 'arrow-square-out', 'shield-check', 'file-audio',
  'device-mobile', 'timer', 'screencast', 'user-focus', 'play', 'pause', 'minus',
  'plus', 'flip-horizontal', 'eye', 'eye-slash', 'speaker-high', 'caret-down',
  'wifi-slash', 'lock-simple', 'arrows-clockwise', 'stop', 'record', 'clock',
  'folder-simple', 'magnifying-glass-plus',
  // fill weight
  'record-fill', 'pause-fill', 'play-fill', 'stop-fill', 'check-circle-fill',
  'warning-circle-fill', 'warning-fill', 'info-fill', 'microphone-slash-fill',
];

const CDN = 'https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.2/src';

async function loadSet(weight, dir) {
  if (dir) return JSON.parse(await readFile(path.join(dir, weight, 'selection.json'), 'utf8'));
  const res = await fetch(`${CDN}/${weight}/selection.json`);
  if (!res.ok) throw new Error(`Fetching ${weight} icons failed: HTTP ${res.status}`);
  return res.json();
}

// 1 decimal place on a 1024 grid is far below a pixel at any size we draw.
// Paths may pack numbers with no separator ("0.001.002" is two numbers), so
// every rounded number gets an explicit separator unless its minus sign is one.
const compact = (d) =>
  d.replace(/-?\d*\.\d+/g, (n) => {
    const v = Math.round(parseFloat(n) * 10) / 10;
    return v < 0 ? String(v) : ' ' + String(v === 0 ? 0 : v);
  })
   .replace(/\s+/g, ' ')
   .replace(/([a-zA-Z]) /g, '$1')
   .trim();

const dir = process.argv[2];
const sets = { regular: await loadSet('regular', dir), fill: await loadSet('fill', dir) };
const byName = new Map();
for (const set of Object.values(sets)) {
  for (const icon of set.icons) byName.set(icon.properties.name, icon.icon.paths);
}

const symbols = ICONS.map((name) => {
  const paths = byName.get(name);
  if (!paths) throw new Error(`Unknown Phosphor icon: ${name}`);
  const body = paths.map((d) => `<path d="${compact(d)}"/>`).join('');
  return `<symbol id="i-${name}" viewBox="0 0 1024 1024">${body}</symbol>`;
});

const sprite =
  '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">' +
  symbols.join('') +
  '</svg>';

const out = `// Generated by tools/build-icons.mjs. Do not edit by hand.
// Phosphor Icons (https://phosphoricons.com), MIT License, (c) Phosphor Icons.
// Loaded synchronously at the top of <body> so icons render with the first paint.
(function () {
  var sprite = ${JSON.stringify(sprite)};
  var host = document.createElement('div');
  host.id = 'icon-sprite';
  host.innerHTML = sprite;
  (document.body || document.documentElement).insertBefore(host, (document.body || document.documentElement).firstChild);
})();
`;

const target = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'js', 'icons.js');
await writeFile(target, out);
console.log(`Wrote ${ICONS.length} icons to ${path.relative(process.cwd(), target)} (${(out.length / 1024).toFixed(1)} KB)`);
